using System.Windows;
using System.Windows.Input;
using System.Windows.Media;

namespace Ostrasort.Gui;

public sealed record ModRow(string Pos, string Entry, string Class, string Data, string Notes, Brush Brush);
public sealed record LineVm(string Text, Brush Brush, Thickness Margin);

public partial class MainWindow : Window
{
    private static readonly Brush Normal = Brushes.Black;
    private static readonly Brush Dim = Brushes.Gray;
    private static readonly Brush Good = Brushes.Green;
    private static readonly Brush Warn = new SolidColorBrush(Color.FromRgb(0xB8, 0x6E, 0x00));
    private static readonly Brush Bad = Brushes.Firebrick;

    private readonly GameEnv _env;
    private EngineState? _state;

    public MainWindow(GameEnv env)
    {
        _env = env;
        InitializeComponent();
        TxtTitle.Text = $"Ostrasort v{Program.Version}";
        Rescan();
    }

    // ---------------------------------------------------------------- scan ---

    private void Rescan()
    {
        Mouse.OverrideCursor = Cursors.Wait;
        try
        {
            _state = Engine.Analyze(_env);
            RenderState(_state);
        }
        catch (Exception e)
        {
            MessageBox.Show(this, e.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally { Mouse.OverrideCursor = null; }
    }

    private void RenderState(EngineState s)
    {
        var a = s.Analysis;
        TxtGameInfo.Text = $"{_env.GameRoot}   —   game version {_env.InstalledVersion ?? "unknown"}, found via {_env.DiscoveredVia}";
        TxtCoreInfo.Text = $"Mods: {_env.ModsDir}   —   core: {s.Scanner.CoreIndex.Count:N0} objects / {s.Scanner.CoreTypes} types" +
                           (s.Scanner.CoreProblemFiles > 0 ? $" ({s.Scanner.CoreProblemFiles} non-standard JSON file(s))" : "");

        // mod table
        var rows = new List<ModRow>();
        var all = a.Registered.Select((m, i) => (Pos: (i + 1).ToString(), Mod: m))
            .Concat(a.UnregisteredLocal.Concat(a.UnregisteredWorkshop).Select(m => (Pos: "-", Mod: m)));
        foreach (var (pos, m) in all)
        {
            var cls = m.Kind == EntryKind.Core ? "core" : m.IsPatch ? "patch" : m.Class.ToString().ToLowerInvariant();
            var data = m.Kind == EntryKind.Core ? $"{s.Scanner.CoreIndex.Count:N0} objects"
                     : m.DataObjects > 0 ? $"{m.DataObjects} objs ({m.CoreOverrides} ovr)" : "-";
            var notes = new List<string>();
            if (!m.Registered) notes.Add("NOT REGISTERED");
            if (m.Dir is null && m.Kind != EntryKind.Core) notes.Add("DEAD ENTRY");
            if (m.IsPatch) notes.Add("generated by Ostrasort");
            if (m.HasPatchers) notes.Add("ships BepInEx patchers");
            if (m.HasPlugins && !m.HasPatchers) notes.Add("plugins");
            if (m.GameVersion is { Length: > 0 } gv && _env.InstalledVersion is { } iv && gv != iv)
                notes.Add($"gameVersion {gv} lags {iv}");
            if (m.JsonErrors.Count > 0) notes.Add($"{m.JsonErrors.Count} JSON problem(s)");
            var brush = notes.Any(n => n.StartsWith("NOT") || n.StartsWith("DEAD") || n.Contains("JSON")) ? Warn : Normal;
            rows.Add(new ModRow(pos, m.Label, cls, data, string.Join("; ", notes), brush));
        }
        ModsGrid.ItemsSource = rows;

        // collisions tab
        var col = new List<LineVm>();
        foreach (var c in a.Collisions)
        {
            col.Add(L($"{c.Key}   — last loaded wins the whole object", Normal));
            for (var i = 0; i < c.Claimants.Count; i++)
                col.Add(L($"{i + 1}. {c.Claimants[i].Label}", Dim, 1));
            foreach (var p in c.Pairs)
            {
                var line = p.Rel switch
                {
                    Relation.SupersetOk => L($"OK — {p.Later.Label} is a superset of {p.Earlier.Label} (+{p.AddedByLater.Length} items); order correct", Good, 1),
                    Relation.Equal => L("OK — identical item sets; only quantities differ, last loaded wins them", Good, 1),
                    Relation.SubsetViolation => L($"WRONG ORDER — {p.Later.Label} drops {p.LostFromEarlier.Length} item(s) {p.Earlier.Label} stocks; the superset must load last", Bad, 1),
                    Relation.Partial when c.ResolvedByPatch => L("RESOLVED — the Ostrasort Patch merges both pools and loads last", Good, 1),
                    Relation.Partial => L($"CONFLICT — neither pool covers the other ({p.Later.Label} drops: {string.Join(", ", p.LostFromEarlier.Take(6))}{(p.LostFromEarlier.Length > 6 ? " …" : "")}). Use the patch button below.", Bad, 1),
                    _ => L($"last loaded ({p.Later.Label}) replaces the object entirely — verify that is intended", Warn, 1),
                };
                col.Add(line);
            }
            col.Add(L("", Normal));
        }
        if (col.Count == 0) col.Add(L("No two mods claim the same object.", Good));
        ListCollisions.ItemsSource = col;
        TabCollisions.Header = $"Collisions ({a.Collisions.Count})";

        // order tab
        var ord = new List<LineVm>();
        if (!a.OrderChanged) ord.Add(L("The current load order satisfies every rule — nothing to change.", Good));
        else
        {
            foreach (var ch in a.Changes)
            {
                var brush = ch.Action switch { "add" => Good, "remove" => Bad, _ => Warn };
                ord.Add(L($"{ch.Action.ToUpperInvariant(),-8} {ch.Entry}", brush));
                ord.Add(L(ch.Reason, Dim, 1));
            }
            ord.Add(L("", Normal));
            ord.Add(L("Resulting order:", Normal));
            for (var i = 0; i < a.SuggestedOrder.Count; i++)
                ord.Add(L($"{i + 1,2}. {a.SuggestedOrder[i]}", Dim, 1));
        }
        ListOrder.ItemsSource = ord;
        TabOrder.Header = a.OrderChanged ? $"Order changes ({a.Changes.Count})" : "Order changes";

        // patch tab
        var pat = new List<LineVm>();
        if (!s.Patch.Exists)
            pat.Add(a.HasUnresolvedConflicts
                ? L("No patch generated yet — use \"Resolve conflicts & generate patch\" to merge the conflicting pools.", Warn)
                : L("No patch needed.", Good));
        else if (s.Patch.Stale)
        {
            foreach (var r in s.Patch.StaleReasons) pat.Add(L($"STALE — {r}", Bad));
            pat.Add(L("Regenerate it with the patch button; your previous decisions are kept where still valid.", Warn));
        }
        else if (s.Patch.Obsolete)
            pat.Add(L("The installed patch is no longer needed (conflicts resolved upstream) — remove it.", Warn));
        else
        {
            pat.Add(L($"Fresh (generated by v{s.Patch.ToolVersion ?? "?"}) — covering {string.Join(", ", s.Patch.CoveredKeys)}", Good));
            if (s.Patch.UnneededKeys.Count > 0)
                pat.Add(L($"No longer needed for {string.Join(", ", s.Patch.UnneededKeys)} (resolved upstream).", Warn));
        }
        ListPatch.ItemsSource = pat;

        // warnings tab
        var warn = new List<LineVm>();
        foreach (var w in a.Warnings) warn.Add(L(w, Warn));
        foreach (var m in a.AllMods.Where(m => m.JsonErrors.Count > 0))
            foreach (var e in m.JsonErrors)
                warn.Add(L($"{m.Label}: {e}", Warn));
        if (warn.Count == 0) warn.Add(L("No warnings.", Good));
        ListWarnings.ItemsSource = warn;
        TabWarnings.Header = warn.Count == 1 && a.Warnings.Count == 0 ? "Warnings" : $"Warnings ({warn.Count})";

        // buttons + status
        var running = GameEnv.IsGameRunning();
        BtnApply.IsEnabled = a.OrderChanged && !running;
        BtnPatch.IsEnabled = Patcher.PatchableConflicts(a).Count > 0 && !running;
        BtnPatch.Content = s.Patch.Stale ? "Refresh patch (decisions kept)" : "Resolve conflicts & generate patch";
        BtnUnpatch.IsEnabled = s.Patch.Exists && !running;

        if (running)
        {
            TxtStatus.Text = "Ostranauts is RUNNING — writes disabled, rescan after closing it.";
            TxtStatus.Foreground = Bad;
        }
        else if (Engine.Actionable(s))
        {
            var n = (a.OrderChanged ? 1 : 0) + (a.HasUnresolvedConflicts ? 1 : 0) +
                    (s.Patch.Stale ? 1 : 0) + (s.Patch.Obsolete ? 1 : 0);
            TxtStatus.Text = $"{n} thing(s) need attention — see the highlighted tabs.";
            TxtStatus.Foreground = Warn;
        }
        else
        {
            TxtStatus.Text = "Everything satisfied — nothing to do.";
            TxtStatus.Foreground = Good;
        }
    }

    private static LineVm L(string text, Brush brush, int indent = 0) =>
        new(text, brush, new Thickness(indent * 18, 1, 0, 1));

    // ------------------------------------------------------------- actions ---

    private bool GateRunning()
    {
        if (!GameEnv.IsGameRunning()) return true;
        MessageBox.Show(this, "Ostranauts is running — close it first. Nothing was written.",
            "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Warning);
        Rescan();
        return false;
    }

    private void Rescan_Click(object sender, RoutedEventArgs e) => Rescan();

    private void Apply_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        try
        {
            _state.Lo.Write(_state.Analysis.SuggestedOrder);
            Rescan();
            MessageBox.Show(this, "Load order applied. The previous file was saved as loading_order.json.bak.",
                "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private void Patch_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        try
        {
            var plan = Patcher.PlanMerge(_env, _state.Analysis);
            if (plan.Pools.Count == 0)
            {
                MessageBox.Show(this, "There are no partial-overlap shop-pool conflicts to merge.",
                    "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            if (plan.ContestedItems.Any())
            {
                var dlg = new ResolverDialog(plan) { Owner = this };
                if (dlg.ShowDialog() != true) return;
            }
            Patcher.Generate(_env, plan, _env.InstalledVersion, Program.Version);
            Rescan();
            MessageBox.Show(this, "Patch generated and registered last in the load order.",
                "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private void Unpatch_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        if (MessageBox.Show(this, "Remove the generated Ostrasort Patch (folder + load-order entry)?",
                "Ostrasort", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) return;
        try
        {
            Patcher.Remove(_env);
            Rescan();
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }
}
