using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace Ostrasort.Gui;

public sealed record ModRow(string Pos, string Name, string Source, string Class, string Data,
                            string WorkshopId, string Notes, Brush Brush, string? Dir, string Tooltip,
                            ModEntry M, bool Draggable);
public sealed record LineVm(string Text, Brush Brush, Thickness Margin);

public partial class MainWindow : Window
{
    private static readonly Brush Normal = Brushes.Black;
    private static readonly Brush Dim = Brushes.Gray;
    private static readonly Brush Good = Brushes.Green;
    private static readonly Brush Warn = new SolidColorBrush(Color.FromRgb(0xB8, 0x6E, 0x00));
    private static readonly Brush Bad = Brushes.Firebrick;

    private static readonly HttpClient Http = CreateHttp();
    private static HttpClient CreateHttp()
    {
        var c = new HttpClient { Timeout = TimeSpan.FromSeconds(5) };
        c.DefaultRequestHeaders.UserAgent.ParseAdd("Ostrasort");
        return c;
    }

    private readonly GameEnv _env;
    private readonly GuiSettings _settings;
    private EngineState? _state;
    private System.Collections.ObjectModel.ObservableCollection<ModRow> _rows = new();
    private bool _manualDirty;
    private bool _busy;
    private DateTime _lastScan = DateTime.MinValue;
    private Point _dragStart;
    private ModRow? _dragRow;

    public MainWindow(GameEnv env)
    {
        _env = env;
        _settings = GuiSettings.Load();
        InitializeComponent();
        RestoreWindowState();
        TxtTitle.Text = $"Ostrasort v{Program.Version}";
        ChkTidy.IsChecked = _settings.Tidy;
        if (_settings.Tab >= 0 && _settings.Tab < Tabs.Items.Count) Tabs.SelectedIndex = _settings.Tab;
        Rescan();
        _ = CheckForUpdateAsync();
    }

    // ---------------------------------------------------------------- scan ---

    private void Rescan()
    {
        Mouse.OverrideCursor = Cursors.Wait;
        try
        {
            _manualDirty = false;
            _state = Engine.Analyze(_env, ChkTidy.IsChecked == true);
            RenderState(_state);
        }
        catch (Exception e)
        {
            MessageBox.Show(this, e.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            Mouse.OverrideCursor = null;
            _lastScan = DateTime.Now;
        }
    }

    private void RenderState(EngineState s)
    {
        var a = s.Analysis;
        RunGamePath.Text = _env.GameRoot + "  ";
        RunFoundVia.Text = $"   (found via {_env.DiscoveredVia})";
        RunModsPath.Text = _env.ModsDir + "  ";
        TxtVersions.Text = $"game {_env.InstalledVersion ?? "unknown"}    ·    Ostrasort v{Program.Version}";
        TxtCoreInfo.Text = $"{s.Scanner.CoreIndex.Count:N0} objects across {s.Scanner.CoreTypes} types" +
                           (s.Scanner.CoreProblemFiles > 0 ? $"   ({s.Scanner.CoreProblemFiles} non-standard JSON file(s))" : "");

        // mod table
        _rows = new System.Collections.ObjectModel.ObservableCollection<ModRow>();
        var all = a.Registered.Select((m, i) => (Pos: (i + 1).ToString(), Mod: m))
            .Concat(a.UnregisteredLocal.Concat(a.UnregisteredWorkshop).Select(m => (Pos: "-", Mod: m)));
        foreach (var (pos, m) in all) _rows.Add(BuildRow(pos, m));
        ModsGrid.ItemsSource = _rows;
        ApplyFilter();

        RenderTabs(s);
        UpdateActionBar(s);
    }

    private ModRow BuildRow(string pos, ModEntry m)
    {
        var s = _state!;
        var cls = m.Kind == EntryKind.Core ? "core" : m.IsPatch ? "patch" : m.Class.ToString().ToLowerInvariant();
        var data = m.Kind == EntryKind.Core ? $"{s.Scanner.CoreIndex.Count:N0} objects"
                 : m.DataObjects > 0 ? $"{m.DataObjects} objs ({m.CoreOverrides} ovr)" : "-";
        var source = m.Kind switch
        {
            EntryKind.Core => "game",
            EntryKind.Workshop => "Workshop",
            _ when m.IsPatch => "generated",
            _ => "local",
        };
        var notes = new List<string>();
        if (!m.Registered) notes.Add("NOT REGISTERED");
        if (m.Dir is null && m.Kind != EntryKind.Core) notes.Add("DEAD ENTRY");
        if (m.IsPatch) notes.Add("generated by Ostrasort");
        if (m.HasPatchers) notes.Add("ships BepInEx patchers");
        if (m.HasPlugins && !m.HasPatchers) notes.Add("plugins");
        if (m.GameVersion is { Length: > 0 } gv && _env.InstalledVersion is { } iv && gv != iv)
            notes.Add($"gameVersion {gv} lags {iv}");
        if (m.JsonErrors.Count > 0) notes.Add($"{m.JsonErrors.Count} JSON problem(s)");
        var brush = notes.Any(n => n.StartsWith("NOT") || n.StartsWith("DEAD") || n.Contains("JSON")) ? Warn : Normal;
        var name = m.Kind == EntryKind.Core ? "core (base game data)" : m.DisplayName ?? m.Name;
        var tooltip = m.Dir ?? m.Raw;
        if (m.Kind != EntryKind.Core && m.Dir is not null) tooltip += "\n(double-click to open the folder)";
        var draggable = m.Registered && m.Kind != EntryKind.Core;
        return new ModRow(pos, name, source, cls, data, m.WorkshopId ?? "-",
            string.Join("; ", notes), brush, m.Dir, tooltip, m, draggable);
    }

    private void RenderTabs(EngineState s)
    {
        var a = s.Analysis;

        var col = new List<LineVm>();
        foreach (var c in a.Collisions)
        {
            col.Add(L($"{c.Key}   — last loaded wins the whole object", Normal));
            for (var i = 0; i < c.Claimants.Count; i++)
                col.Add(L($"{i + 1}. {c.Claimants[i].Label}", Dim, 1));
            foreach (var p in c.Pairs)
            {
                var line = p.Rel switch
                {
                    Relation.SupersetOk => L($"OK — {p.Later.Label} is a superset of {p.Earlier.Label} (+{p.AddedByLater.Length} items); order correct", Good, 1),
                    Relation.Equal => L("OK — identical item sets; only quantities differ, last loaded wins them", Good, 1),
                    Relation.SubsetViolation => L($"WRONG ORDER — {p.Later.Label} drops {p.LostFromEarlier.Length} item(s) {p.Earlier.Label} stocks; the superset must load last", Bad, 1),
                    Relation.Partial when c.ResolvedByPatch => L("RESOLVED — the Ostrasort Patch merges both pools and loads last", Good, 1),
                    Relation.Partial => L($"CONFLICT — neither pool covers the other ({p.Later.Label} drops: {string.Join(", ", p.LostFromEarlier.Take(6))}{(p.LostFromEarlier.Length > 6 ? " …" : "")}). Use the patch button below.", Bad, 1),
                    _ => L($"last loaded ({p.Later.Label}) replaces the object entirely — see field analysis:", Warn, 1),
                };
                col.Add(line);
            }
            foreach (var n in c.FieldNotes)
                col.Add(L(n, n.StartsWith("BOTH") ? Bad : n.StartsWith("disjoint") ? Good : Dim, 2));
            col.Add(L("", Normal));
        }
        if (col.Count == 0) col.Add(L("No two mods claim the same object.", Good));
        ListCollisions.ItemsSource = col;
        TabCollisions.Header = $"Collisions ({a.Collisions.Count})";

        var ord = new List<LineVm>();
        if (!a.OrderChanged) ord.Add(L("The current load order satisfies every rule — nothing to change.", Good));
        else
        {
            foreach (var ch in a.Changes)
            {
                var brush = ch.Action switch { "add" => Good, "remove" => Bad, _ => Warn };
                ord.Add(L($"{ch.Action.ToUpperInvariant(),-8} {ch.Entry}", brush));
                ord.Add(L(ch.Reason, Dim, 1));
            }
            ord.Add(L("", Normal));
            ord.Add(L("Resulting order:", Normal));
            for (var i = 0; i < a.SuggestedOrder.Count; i++)
                ord.Add(L($"{i + 1,2}. {a.SuggestedOrder[i]}", Dim, 1));
        }
        ListOrder.ItemsSource = ord;
        TabOrder.Header = a.OrderChanged ? $"Order changes ({a.Changes.Count})" : "Order changes";

        var pat = new List<LineVm>();
        if (!s.Patch.Exists)
            pat.Add(a.HasUnresolvedConflicts
                ? L("No patch generated yet — use \"Resolve conflicts & generate patch\" to merge the conflicting pools.", Warn)
                : L("No patch needed.", Good));
        else if (s.Patch.Stale)
        {
            foreach (var r in s.Patch.StaleReasons) pat.Add(L($"STALE — {r}", Bad));
            pat.Add(L("Regenerate it with the patch button; your previous decisions are kept where still valid.", Warn));
        }
        else if (s.Patch.Obsolete)
            pat.Add(L("The installed patch is no longer needed (conflicts resolved upstream) — remove it.", Warn));
        else
        {
            pat.Add(L($"Fresh (generated by v{s.Patch.ToolVersion ?? "?"}) — covering {string.Join(", ", s.Patch.CoveredKeys)}", Good));
            if (s.Patch.UnneededKeys.Count > 0)
                pat.Add(L($"No longer needed for {string.Join(", ", s.Patch.UnneededKeys)} (resolved upstream).", Warn));
        }
        ListPatch.ItemsSource = pat;

        var warn = new List<LineVm>();
        foreach (var w in a.Warnings) warn.Add(L(w, Warn));
        foreach (var m in a.AllMods.Where(m => m.JsonErrors.Count > 0))
            foreach (var e in m.JsonErrors)
                warn.Add(L($"{m.Label}: {e}", Warn));
        var warnCount = warn.Count;
        if (warn.Count == 0) warn.Add(L("No warnings.", Good));
        ListWarnings.ItemsSource = warn;
        TabWarnings.Header = warnCount == 0 ? "Warnings" : $"Warnings ({warnCount})";
    }

    private void UpdateActionBar(EngineState s)
    {
        var a = s.Analysis;
        var running = GameEnv.IsGameRunning();
        var bak = _env.LoadingOrderPath + ".bak";

        BtnApply.IsEnabled = (_manualDirty || a.OrderChanged) && !running;
        BtnApply.Content = _manualDirty ? "Apply manual order" : "Apply suggested order";
        BtnPatch.IsEnabled = Patcher.PatchableConflicts(a).Count > 0 && !running;
        BtnPatch.Content = s.Patch.Stale ? "Refresh patch (decisions kept)" : "Resolve conflicts & generate patch";
        BtnUnpatch.IsEnabled = s.Patch.Exists && !running;
        BtnRestoreBak.IsEnabled = File.Exists(bak) && !running;
        BtnRestoreBak.ToolTip = File.Exists(bak)
            ? $"Swap loading_order.json with the backup from {File.GetLastWriteTime(bak):yyyy-MM-dd HH:mm:ss} (restoring is reversible - it swaps)"
            : "No loading_order.json.bak exists yet";
        BtnLaunch.IsEnabled = !running;
        LinkReset.IsEnabled = _manualDirty;
        TxtDragHint.Text = _manualDirty ? "manual arrangement pending — apply or reset" : "drag rows to reorder manually";

        if (running)
        {
            RunStatus.Text = "Ostranauts is RUNNING — writes disabled, rescan after closing it.  ";
            RunStatus.Foreground = Bad;
        }
        else if (_manualDirty)
        {
            var issues = Analysis.ValidateOrder(RegisteredEntriesInVisualOrder());
            RunStatus.Text = issues.Count == 0
                ? "Manual arrangement pending — no rule violations.  "
                : $"Manual arrangement pending — {issues.Count} rule issue(s), see tooltip.  ";
            RunStatus.Foreground = issues.Count == 0 ? Warn : Bad;
            ((TextBlock)RunStatus.Parent!).ToolTip = issues.Count == 0 ? null : string.Join("\n", issues);
        }
        else if (Engine.Actionable(s))
        {
            var n = (a.OrderChanged ? 1 : 0) + (a.HasUnresolvedConflicts ? 1 : 0) +
                    (s.Patch.Stale ? 1 : 0) + (s.Patch.Obsolete ? 1 : 0);
            RunStatus.Text = $"{n} thing(s) need attention — see the highlighted tabs.  ";
            RunStatus.Foreground = Warn;
            ((TextBlock)RunStatus.Parent!).ToolTip = null;
        }
        else
        {
            RunStatus.Text = "Everything satisfied — nothing to do.  ";
            RunStatus.Foreground = Good;
            ((TextBlock)RunStatus.Parent!).ToolTip = null;
        }
        LinkReset.Inlines.Clear();
        LinkReset.Inlines.Add(_manualDirty ? "reset arrangement" : "");
    }

    private static LineVm L(string text, Brush brush, int indent = 0) =>
        new(text, brush, new Thickness(indent * 18, 1, 0, 1));

    // ------------------------------------------------------------- filtering ---

    private void ApplyFilter()
    {
        var view = CollectionViewSource.GetDefaultView(_rows);
        var needle = TxtFilter.Text.Trim();
        view.Filter = string.IsNullOrEmpty(needle)
            ? null
            : o => o is ModRow r &&
                   (r.Name.Contains(needle, StringComparison.OrdinalIgnoreCase)
                    || r.WorkshopId.Contains(needle, StringComparison.OrdinalIgnoreCase)
                    || r.Class.Contains(needle, StringComparison.OrdinalIgnoreCase)
                    || r.Source.Contains(needle, StringComparison.OrdinalIgnoreCase)
                    || r.Notes.Contains(needle, StringComparison.OrdinalIgnoreCase));
    }

    private void Filter_Changed(object sender, TextChangedEventArgs e)
    {
        if (_rows.Count > 0) ApplyFilter();
    }

    // ------------------------------------------------------------ drag-drop ---

    private static DataGridRow? RowUnder(DependencyObject? d)
    {
        while (d is not null and not DataGridRow) d = VisualTreeHelper.GetParent(d);
        return d as DataGridRow;
    }

    private void ModsGrid_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        _dragStart = e.GetPosition(null);
        _dragRow = RowUnder(e.OriginalSource as DependencyObject)?.Item as ModRow;
    }

    private void ModsGrid_PreviewMouseMove(object sender, MouseEventArgs e)
    {
        if (e.LeftButton != MouseButtonState.Pressed || _dragRow is null) return;
        if (!string.IsNullOrEmpty(TxtFilter.Text)) return;            // no reordering a filtered view
        if (!_dragRow.Draggable) return;
        var delta = e.GetPosition(null) - _dragStart;
        if (Math.Abs(delta.X) < SystemParameters.MinimumHorizontalDragDistance &&
            Math.Abs(delta.Y) < SystemParameters.MinimumVerticalDragDistance) return;
        DragDrop.DoDragDrop(ModsGrid, _dragRow, DragDropEffects.Move);
        _dragRow = null;
    }

    private void ModsGrid_DragOver(object sender, DragEventArgs e)
    {
        e.Effects = e.Data.GetDataPresent(typeof(ModRow)) ? DragDropEffects.Move : DragDropEffects.None;
        e.Handled = true;
    }

    private void ModsGrid_Drop(object sender, DragEventArgs e)
    {
        if (e.Data.GetData(typeof(ModRow)) is not ModRow dragged || !dragged.Draggable) return;
        var target = RowUnder(e.OriginalSource as DependencyObject)?.Item as ModRow;
        if (target is null || ReferenceEquals(target, dragged)) return;

        var from = _rows.IndexOf(dragged);
        var to = _rows.IndexOf(target);
        if (from < 0 || to < 0) return;

        // clamp into the registered segment, below core
        var lastRegistered = _rows.Select((r, i) => (r, i)).Where(x => x.r.M.Registered).Max(x => x.i);
        to = Math.Clamp(to, 1, lastRegistered);
        if (to == from) return;

        _rows.RemoveAt(from);
        _rows.Insert(to, dragged);
        Renumber();
        _manualDirty = true;
        if (_state is not null) UpdateActionBar(_state);
    }

    private void Renumber()
    {
        var n = 0;
        for (var i = 0; i < _rows.Count; i++)
            if (_rows[i].M.Registered)
                _rows[i] = _rows[i] with { Pos = (++n).ToString() };
    }

    private List<ModEntry> RegisteredEntriesInVisualOrder() =>
        _rows.Where(r => r.M.Registered).Select(r => r.M).ToList();

    private void ResetManual_Click(object sender, RoutedEventArgs e)
    {
        if (_manualDirty) Rescan();
    }

    // --------------------------------------------------------------- actions ---

    private bool GateRunning()
    {
        if (!GameEnv.IsGameRunning()) return true;
        MessageBox.Show(this, "Ostranauts is running — close it first. Nothing was written.",
            "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Warning);
        Rescan();
        return false;
    }

    private void Rescan_Click(object sender, RoutedEventArgs e) => Rescan();

    private void Tidy_Changed(object sender, RoutedEventArgs e)
    {
        _settings.Tidy = ChkTidy.IsChecked == true;
        if (_state is not null && !_manualDirty) Rescan();
    }

    private void Apply_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        _busy = true;
        try
        {
            List<string> newOrder;
            if (_manualDirty)
            {
                var ordered = RegisteredEntriesInVisualOrder();
                var issues = Analysis.ValidateOrder(ordered);
                if (issues.Any(i => i.StartsWith("BLOCK:")))
                {
                    MessageBox.Show(this, string.Join("\n", issues), "Ostrasort",
                        MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }
                if (issues.Count > 0 && MessageBox.Show(this,
                        "This arrangement has rule warnings:\n\n" + string.Join("\n", issues) +
                        "\n\nApply it anyway?", "Ostrasort",
                        MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes)
                    return;
                newOrder = ordered.Select(m => m.Raw).ToList();
            }
            else
            {
                newOrder = _state.Analysis.SuggestedOrder;
            }

            LoadOrderFile.Read(_env.LoadingOrderPath).Write(newOrder);
            Rescan();
            MessageBox.Show(this, "Load order applied. The previous file was saved as loading_order.json.bak.",
                "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally { _busy = false; }
    }

    private void Patch_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        _busy = true;
        try
        {
            var plan = Patcher.PlanMerge(_env, _state.Analysis);
            if (plan.Pools.Count == 0)
            {
                MessageBox.Show(this, "There are no partial-overlap shop-pool conflicts to merge.",
                    "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            if (plan.ContestedItems.Any())
            {
                var dlg = new ResolverDialog(plan) { Owner = this };
                if (dlg.ShowDialog() != true) return;
            }
            Patcher.Generate(_env, plan, _env.InstalledVersion, Program.Version);
            Rescan();
            MessageBox.Show(this, "Patch generated and registered last in the load order.",
                "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally { _busy = false; }
    }

    private void Unpatch_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null || !GateRunning()) return;
        if (MessageBox.Show(this, "Remove the generated Ostrasort Patch (folder + load-order entry)?",
                "Ostrasort", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) return;
        _busy = true;
        try
        {
            Patcher.Remove(_env);
            Rescan();
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally { _busy = false; }
    }

    private void RestoreBak_Click(object sender, RoutedEventArgs e)
    {
        if (!GateRunning()) return;
        var live = _env.LoadingOrderPath;
        var bak = live + ".bak";
        if (!File.Exists(bak)) return;
        _busy = true;
        try
        {
            var bakText = File.ReadAllText(bak);
            if (!bakText.TrimStart().StartsWith('['))
            {
                MessageBox.Show(this, "The .bak is not a top-level JSON array — refusing to restore it.",
                    "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }
            if (MessageBox.Show(this,
                    $"Swap loading_order.json with the backup from {File.GetLastWriteTime(bak):yyyy-MM-dd HH:mm:ss}?\n\n" +
                    "The current file becomes the new .bak, so restoring is reversible.",
                    "Ostrasort", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes)
                return;
            var liveText = File.ReadAllText(live);
            File.WriteAllText(live, bakText);
            File.WriteAllText(bak, liveText);
            Rescan();
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally { _busy = false; }
    }

    private void Launch_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            Process.Start(new ProcessStartInfo("steam://rungameid/1022980") { UseShellExecute = true });
            RunStatus.Text = "Launching Ostranauts via Steam…  ";
            RunStatus.Foreground = Dim;
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    // ------------------------------------------------------- report export ---

    private void CopyReport_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null) return;
        Clipboard.SetText(TextReport.Build(_env, _state, Program.Version));
        RunStatus.Text = "Report copied to the clipboard.  ";
        RunStatus.Foreground = Good;
    }

    private void SaveReport_Click(object sender, RoutedEventArgs e)
    {
        if (_state is null) return;
        var dlg = new Microsoft.Win32.SaveFileDialog
        {
            FileName = "ostrasort-report.txt",
            Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*",
        };
        if (dlg.ShowDialog(this) != true) return;
        File.WriteAllText(dlg.FileName, TextReport.Build(_env, _state, Program.Version));
    }

    // ---------------------------------------------------------- context menu ---

    private void ModsGrid_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (RowUnder(e.OriginalSource as DependencyObject) is { } row) row.IsSelected = true;
    }

    private void RowMenu_Opened(object sender, RoutedEventArgs e)
    {
        var row = ModsGrid.SelectedItem as ModRow;
        MenuOpenFolder.IsEnabled = row?.Dir is not null;
        MenuOpenWorkshop.IsEnabled = row?.M.WorkshopId is not null;
        MenuCopyName.IsEnabled = row is not null;
        MenuCopyId.IsEnabled = row?.M.WorkshopId is not null;
    }

    private void MenuOpenFolder_Click(object sender, RoutedEventArgs e)
    {
        if (ModsGrid.SelectedItem is ModRow { Dir: not null } row) OpenFolder(row.Dir);
    }

    private void MenuOpenWorkshop_Click(object sender, RoutedEventArgs e)
    {
        if (ModsGrid.SelectedItem is ModRow { M.WorkshopId: { } id })
            Process.Start(new ProcessStartInfo($"https://steamcommunity.com/sharedfiles/filedetails/?id={id}")
            { UseShellExecute = true });
    }

    private void MenuCopyName_Click(object sender, RoutedEventArgs e)
    {
        if (ModsGrid.SelectedItem is ModRow row) Clipboard.SetText(row.Name);
    }

    private void MenuCopyId_Click(object sender, RoutedEventArgs e)
    {
        if (ModsGrid.SelectedItem is ModRow { M.WorkshopId: { } id }) Clipboard.SetText(id);
    }

    // ----------------------------------------------------- window behaviour ---

    private static void OpenFolder(string? path)
    {
        if (path is null || !Directory.Exists(path)) return;
        Process.Start(new ProcessStartInfo("explorer.exe", $"\"{path}\"") { UseShellExecute = true });
    }

    private void OpenGame_Click(object sender, RoutedEventArgs e) => OpenFolder(_env.GameRoot);
    private void OpenMods_Click(object sender, RoutedEventArgs e) => OpenFolder(_env.ModsDir);

    private void ModsGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (ModsGrid.SelectedItem is ModRow { Dir: not null } row) OpenFolder(row.Dir);
    }

    /// <summary>Rescan when the window regains focus (e.g. after closing the game) - debounced and never over a manual arrangement.</summary>
    private void Window_Activated(object sender, EventArgs e)
    {
        if (_busy || _manualDirty || _state is null) return;
        if ((DateTime.Now - _lastScan).TotalSeconds < 5) return;
        Rescan();
    }

    private void Window_Closing(object sender, CancelEventArgs e)
    {
        _settings.Maximized = WindowState == WindowState.Maximized;
        if (WindowState == WindowState.Normal)
        {
            _settings.Left = Left; _settings.Top = Top;
            _settings.Width = Width; _settings.Height = Height;
        }
        _settings.Tidy = ChkTidy.IsChecked == true;
        _settings.Tab = Tabs.SelectedIndex;
        _settings.Save();
    }

    private void RestoreWindowState()
    {
        if (!double.IsNaN(_settings.Left) && !double.IsNaN(_settings.Top) &&
            _settings.Left < SystemParameters.VirtualScreenWidth - 100 &&
            _settings.Top < SystemParameters.VirtualScreenHeight - 100)
        {
            WindowStartupLocation = WindowStartupLocation.Manual;
            Left = Math.Max(_settings.Left, SystemParameters.VirtualScreenLeft);
            Top = Math.Max(_settings.Top, SystemParameters.VirtualScreenTop);
        }
        Width = Math.Max(_settings.Width, MinWidth);
        Height = Math.Max(_settings.Height, MinHeight);
        if (_settings.Maximized) WindowState = WindowState.Maximized;
    }

    // ---------------------------------------------------------- update check ---

    private async Task CheckForUpdateAsync()
    {
        try
        {
            var json = await Http.GetStringAsync("https://api.github.com/repos/Valtora/Ostrasort/releases/latest");
            using var doc = JsonDocument.Parse(json);
            var tag = doc.RootElement.GetProperty("tag_name").GetString() ?? "";
            var url = doc.RootElement.TryGetProperty("html_url", out var u) ? u.GetString() : null;
            if (ParseVersion(tag) > ParseVersion(Program.Version))
            {
                LinkUpdate.Inlines.Clear();
                LinkUpdate.Inlines.Add($"{tag} available");
                LinkUpdate.NavigateUri = new Uri(url ?? "https://github.com/Valtora/Ostrasort/releases");
                TxtUpdate.Visibility = Visibility.Visible;
            }
        }
        catch { /* offline, rate-limited, or no releases yet - stay quiet */ }
    }

    private static Version ParseVersion(string s) =>
        Version.TryParse(s.TrimStart('v', 'V').Split('+', '-')[0], out var v) ? v : new Version(0, 0);

    private void Update_Click(object sender, RoutedEventArgs e)
    {
        if (LinkUpdate.NavigateUri is { } uri)
            Process.Start(new ProcessStartInfo(uri.ToString()) { UseShellExecute = true });
    }
}
