using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;

namespace Ostrasort.Gui;

/// <summary>What the user asked the main window to do when the dialog closed.</summary>
public enum ModDetailAction { None, Enable, Disable, Register, Remove }

/// <summary>
/// Everything about one mod in one place: its facts, plain-language status
/// notes, JSON problems, the game-log lines attributed to it, and every
/// conflict it participates in (each opening the side-by-side detail view) -
/// with the actions (enable/disable, register, remove) right there. The main
/// window executes the chosen action after the dialog closes, so every write
/// still goes through its usual gates and undo capture.
/// </summary>
public partial class ModDetailDialog : Window
{
    private static Brush Dim => ThemeManager.Dim;
    private static Brush Good => ThemeManager.Good;
    private static Brush Warn => ThemeManager.Warn;
    private static Brush Bad => ThemeManager.Bad;

    private readonly GameEnv _env;
    private readonly Analysis _analysis;
    private readonly ModEntry _m;

    public ModDetailAction Action { get; private set; } = ModDetailAction.None;

    public ModDetailDialog(GameEnv env, Analysis analysis, ModEntry m, string statusGlyph, Brush statusBrush, bool canToggle)
    {
        _env = env;
        _analysis = analysis;
        _m = m;
        InitializeComponent();

        TxtStatusGlyph.Text = statusGlyph;
        TxtStatusGlyph.Foreground = statusBrush;
        TxtTitle.Text = m.DisplayName ?? m.Name;
        Title = $"Mod details - {m.DisplayName ?? m.Name}";
        TxtSubtitle.Text = Subtitle(m);

        BtnToggle.Content = m.Disabled ? "Enable" : "Disable";
        BtnToggle.ToolTip = m.Disabled
            ? "Let the game load this mod again."
            : "Keep the mod installed and listed, but have the game skip it (the same toggle the in-game MODS screen has).";
        BtnToggle.Visibility = canToggle ? Visibility.Visible : Visibility.Collapsed;
        BtnRegister.Visibility =
            m is { Registered: false, Kind: not EntryKind.Core } && !m.IsPatch ? Visibility.Visible : Visibility.Collapsed;
        BtnRemove.Visibility =
            m.IsPatch || m is { Kind: EntryKind.Local or EntryKind.PluginDir, Dir: not null }
                ? Visibility.Visible : Visibility.Collapsed;

        BuildBody();
    }

    private static string Subtitle(ModEntry m)
    {
        var bits = new List<string>
        {
            m.Kind switch
            {
                EntryKind.Core => "the base game's own data",
                EntryKind.Workshop => "installed from the Steam Workshop",
                EntryKind.PluginDir => "a data mod inside BepInEx\\plugins",
                _ when m.IsPatch => "generated by Ostrasort",
                _ => "a local mod folder",
            },
        };
        if (m.ModVersion is { Length: > 0 } v) bits.Add($"version {v}");
        bits.Add(m.Disabled ? "disabled" : m.Registered ? "loads with the game" : "not in the load list");
        return string.Join(", ", bits) + ".";
    }

    private void BuildBody()
    {
        var m = _m;

        // ---- facts ----
        Section("About");
        if (m.Dir is { } dir) LinkLine($"Folder: {dir}", "open", () => OpenPath(dir));
        if (m.WorkshopId is { } id)
            LinkLine($"Workshop ID: {id}", "open page",
                () => OpenUrl($"https://steamcommunity.com/sharedfiles/filedetails/?id={id}"));
        if (m.DataObjects > 0)
            Line($"Changes {m.DataObjects} game object(s), {m.CoreOverrides} of them base-game overrides.", Dim);
        if (m.HasPlugins || m.HasPatchers)
            Line("Ships code (BepInEx " + (m.HasPatchers ? "patchers" : "plugins") + ") that runs inside the game.", Dim);

        // ---- status notes ----
        var notes = m.NoteLines(_env.InstalledVersion);
        if (notes.Count > 0)
        {
            Section("Status");
            foreach (var n in notes)
                Line("• " + n, n.StartsWith("NOT") || n.StartsWith("DEAD") || n.Contains("JSON") || n.Contains("game-log") ? Warn : Dim);
        }

        // ---- JSON problems ----
        if (m.JsonErrors.Count > 0)
        {
            Section("File problems");
            foreach (var e in m.JsonErrors) Line("• " + e, Bad);
        }

        // ---- attributed game-log issues ----
        if (m.LogNotes.Count > 0)
        {
            Section("Reported by the game (last launch)");
            foreach (var n in m.LogNotes) Line("• " + n, Bad);
            Line("If this mod keeps causing problems, disable it below and relaunch the game to confirm.", Dim);
        }

        // ---- conflicts this mod participates in ----
        var conflicts = _analysis.Collisions.Where(c => c.Claimants.Contains(m)).ToList();
        if (conflicts.Count > 0)
        {
            Section($"Conflicts with other mods ({conflicts.Count})");
            foreach (var c in conflicts)
            {
                var others = c.Claimants.Where(x => x != m).Select(x => x.DisplayName ?? x.Name).ToList();
                var needs = CollisionView.NeedsAttention(c);
                var what = $"{c.ObjName} ({CollisionView.TypeLabel(c.Type)})"
                           + (c.FriendlyName is { Length: > 0 } f ? $" \"{f}\"" : "")
                           + " with " + string.Join(", ", others)
                           + (needs ? " (needs attention)" : " (handled)");
                var col = c;
                LinkLine("• " + what, "details", () => OpenConflict(col), needs ? Warn : Dim);
            }
        }

        if (Body.Children.Count == 0)
            Line("Nothing notable about this mod.", Dim);
    }

    // ------------------------------------------------------------ plumbing ---

    private void Section(string title)
    {
        Body.Children.Add(new TextBlock
        {
            Text = title,
            FontWeight = FontWeights.SemiBold,
            FontSize = 13.5,
            Margin = new Thickness(0, Body.Children.Count == 0 ? 0 : 12, 0, 4),
        });
    }

    private void Line(string text, Brush brush)
    {
        Body.Children.Add(new TextBlock
        {
            Text = text,
            Foreground = brush,
            TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 1, 0, 1),
        });
    }

    private void LinkLine(string text, string linkText, Action onClick, Brush? brush = null)
    {
        var tb = new TextBlock { TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 1, 0, 1) };
        tb.Inlines.Add(new Run(text + "  ") { Foreground = brush ?? ThemeManager.Normal });
        var link = new Hyperlink(new Run(linkText));
        link.Click += (_, _) => onClick();
        tb.Inlines.Add(link);
        Body.Children.Add(tb);
    }

    private void OpenConflict(Collision c)
    {
        try
        {
            new CollisionDetailDialog(_env, c, _analysis.IgnorePatterns) { Owner = this }.ShowDialog();
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private static void OpenPath(string path)
    {
        if (Directory.Exists(path))
            Process.Start(new ProcessStartInfo("explorer.exe", $"\"{path}\"") { UseShellExecute = true });
    }

    private void OpenUrl(string url)
    {
        try { Process.Start(new ProcessStartInfo(url) { UseShellExecute = true }); }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Ostrasort", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private void CloseWith(ModDetailAction action)
    {
        Action = action;
        DialogResult = true;
    }

    private void Toggle_Click(object sender, RoutedEventArgs e) =>
        CloseWith(_m.Disabled ? ModDetailAction.Enable : ModDetailAction.Disable);

    private void Register_Click(object sender, RoutedEventArgs e) => CloseWith(ModDetailAction.Register);

    private void Remove_Click(object sender, RoutedEventArgs e) => CloseWith(ModDetailAction.Remove);
}
