using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Ostrasort;

public sealed class PatchInfo
{
    public bool Exists { get; init; }
    public string? Dir { get; init; }
    public string? ToolVersion { get; set; }
    public List<string> CoveredKeys { get; } = new();
    public List<string> StaleReasons { get; } = new();
    public List<string> UnneededKeys { get; } = new();
    public bool Stale => StaleReasons.Count > 0;
    public bool Obsolete => Exists && CoveredKeys.Count == 0 && !Stale;   // conflicts resolved upstream
}

// ------------------------------------------------------------- merge plan ---

/// <summary>One mod's candidate entry for an item ("ItmChair01Loose=1.0x21").</summary>
public sealed record MergeOption(string SourceId, string SourceLabel, string Entry);

/// <summary>
/// One item of a merged pool. Options are in claimant load order. An item is
/// contested when two claimants disagree on the full entry text; contested
/// items need a decision - the player's, or the headless fallback.
/// </summary>
public sealed class MergeItem
{
    public required string Token { get; init; }
    public required List<MergeOption> Options { get; init; }
    public string? ChosenSourceId { get; set; }
    public bool AutoResolved { get; set; }        // decided by the headless fallback, not a person

    public bool Contested => Options.Select(o => o.Entry).Distinct(StringComparer.Ordinal).Count() > 1;
    public bool NeedsDecision => Contested && ChosenSourceId is null;
    public MergeOption Resolved =>
        Options.LastOrDefault(o => o.SourceId == ChosenSourceId) ?? Options[^1];
}

public sealed class PoolPlan
{
    public required Collision Collision { get; init; }
    public required JsonNode BaseObject { get; init; }     // last claimant's object (non-pool fields win)
    public required List<MergeItem> LootItems { get; init; }
    public required List<MergeItem> CoItems { get; init; }
    public IEnumerable<MergeItem> AllItems => LootItems.Concat(CoItems);
}

public sealed class MergePlan
{
    public required List<PoolPlan> Pools { get; init; }
    public IEnumerable<MergeItem> Unresolved => Pools.SelectMany(p => p.AllItems).Where(i => i.NeedsDecision);
    public IEnumerable<MergeItem> ContestedItems => Pools.SelectMany(p => p.AllItems).Where(i => i.Contested);
}

/// <summary>
/// Generates and maintains the "OstrasortPatch" mod: for shop-pool collisions
/// where neither mod's pool covers the other (no load order fixes those), it
/// writes a merged union pool that loads last. Items only one mod stocks are
/// always kept; items with disagreeing entries are decided by the player (the
/// resolver UI) or, headless, fall back to the later-loaded mod's entry and
/// are marked auto so the next interactive run offers them for review.
/// The folder is wholly owned by Ostrasort: never hand-edited, safe to delete,
/// regenerated by --patch, removed by --unpatch. A marker file records the
/// source pools (for staleness detection) and every decision (so they stick).
/// </summary>
public static class Patcher
{
    public const string FolderName = "OstrasortPatch";
    public const string MarkerFile = "ostrasort_patch.json";

    private static readonly JsonDocumentOptions Lenient = new()
    {
        AllowTrailingCommas = true,
        CommentHandling = JsonCommentHandling.Skip,
    };
    private static readonly JsonSerializerOptions Indented = new() { WriteIndented = true };

    /// <summary>Collisions --patch can merge: loot pools, every claimant has aLoots, some pair is Partial.</summary>
    public static List<Collision> PatchableConflicts(Analysis a) =>
        a.Collisions.Where(c =>
            c.Type == "loot" &&
            c.Claimants.All(m => m.Claims.TryGetValue((c.Type, c.ObjName), out var l) && l is not null) &&
            c.Pairs.Any(p => p.Rel == Relation.Partial)).ToList();

    public static string ItemsHash(IEnumerable<string> loots) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(
            string.Join("\n", loots.OrderBy(x => x, StringComparer.Ordinal)))));

    private static string SourceId(ModEntry m) => m.Dir ?? m.Raw;

    // ------------------------------------------------------------- inspect ---

    /// <summary>
    /// Reads the marker of an existing patch, verifies it against the current
    /// conflicts, and marks collisions it freshly covers as resolved.
    /// </summary>
    public static PatchInfo Inspect(GameEnv env, Analysis a)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        var marker = Path.Combine(dir, MarkerFile);
        if (!File.Exists(marker))
            return new PatchInfo { Exists = false, Dir = Directory.Exists(dir) ? dir : null };

        var info = new PatchInfo { Exists = true, Dir = dir };
        JsonNode? root;
        try { root = JsonNode.Parse(File.ReadAllText(marker)); }
        catch (JsonException)
        {
            info.StaleReasons.Add("the patch marker file is unreadable - regenerate the patch");
            return info;
        }
        info.ToolVersion = root?["toolVersion"]?.GetValue<string>();

        // marker pool key -> ordered (id, hash) sources it was generated from
        var markerPools = new Dictionary<string, List<(string Id, string Hash)>>(StringComparer.Ordinal);
        foreach (var p in (root?["pools"] as JsonArray) ?? new JsonArray())
        {
            var key = $"{p?["type"]?.GetValue<string>()}/{p?["strName"]?.GetValue<string>()}";
            var sources = new List<(string, string)>();
            foreach (var s in (p?["sources"] as JsonArray) ?? new JsonArray())
                sources.Add((s?["id"]?.GetValue<string>() ?? "", s?["hash"]?.GetValue<string>() ?? ""));
            markerPools[key] = sources;
        }

        var current = PatchableConflicts(a);
        foreach (var c in current)
        {
            if (!markerPools.TryGetValue(c.Key, out var sources))
            {
                info.StaleReasons.Add($"new conflict {c.Key} is not covered yet");
                continue;
            }
            var now = c.Claimants
                .Select(m => (Id: SourceId(m), Hash: ItemsHash(m.Claims[(c.Type, c.ObjName)]!)))
                .ToList();
            if (!now.SequenceEqual(sources))
            {
                info.StaleReasons.Add($"{c.Key}: a source mod's pool (or the mod order) changed since generation");
                continue;
            }
            info.CoveredKeys.Add(c.Key);
            c.ResolvedByPatch = true;
        }
        foreach (var key in markerPools.Keys.Where(k => current.All(c => c.Key != k)))
            info.UnneededKeys.Add(key);

        return info;
    }

    // ---------------------------------------------------------------- plan ---

    /// <summary>
    /// Builds the merge plan for every patchable conflict. Prior decisions are
    /// pre-applied from the marker when the chosen source still offers exactly
    /// the same entry; anything new or changed comes back as needing a decision.
    /// </summary>
    public static MergePlan PlanMerge(GameEnv env, Analysis a)
    {
        var prior = ReadPriorChoices(env);
        var pools = new List<PoolPlan>();

        foreach (var c in PatchableConflicts(a))
        {
            var lootOptions = new Dictionary<string, List<MergeOption>>(StringComparer.Ordinal);
            var lootOrder = new List<string>();
            var coOptions = new Dictionary<string, List<MergeOption>>(StringComparer.Ordinal);
            var coOrder = new List<string>();
            JsonNode? baseObj = null;

            foreach (var m in c.Claimants)
            {
                var obj = LoadPoolObject(m.Dir!, c.Type, c.ObjName);
                if (obj is null) continue;
                baseObj = obj;                       // last claimant's object = base
                Collect(obj["aLoots"], m, lootOrder, lootOptions);
                Collect(obj["aCOs"], m, coOrder, coOptions);
            }
            if (baseObj is null) continue;

            prior.TryGetValue(c.Key, out var priorChoices);
            var plan = new PoolPlan
            {
                Collision = c,
                BaseObject = baseObj,
                LootItems = lootOrder.Select(t => BuildItem(t, lootOptions[t], priorChoices)).ToList(),
                CoItems = coOrder.Select(t => BuildItem(t, coOptions[t], priorChoices)).ToList(),
            };
            pools.Add(plan);
        }
        return new MergePlan { Pools = pools };
    }

    private static void Collect(JsonNode? array, ModEntry source, List<string> order,
                                Dictionary<string, List<MergeOption>> options)
    {
        if (array is not JsonArray ja) return;
        foreach (var n in ja)
        {
            if (n?.GetValueKind() != JsonValueKind.String) continue;
            var entry = n.GetValue<string>();
            var token = entry.Split('=')[0];
            if (!options.TryGetValue(token, out var list))
            {
                options[token] = list = new List<MergeOption>();
                order.Add(token);
            }
            list.Add(new MergeOption(SourceId(source), source.DisplayName ?? source.Name, entry));
        }
    }

    private static MergeItem BuildItem(string token, List<MergeOption> options,
                                       Dictionary<string, (string Source, string Entry, bool Auto)>? prior)
    {
        var item = new MergeItem { Token = token, Options = options };
        if (item.Contested && prior is not null && prior.TryGetValue(token, out var p) &&
            options.Any(o => o.SourceId == p.Source && o.Entry == p.Entry))
        {
            item.ChosenSourceId = p.Source;   // decision still valid - keep it
            item.AutoResolved = p.Auto;
        }
        return item;
    }

    /// <summary>Headless fallback: unresolved contested items take the later-loaded entry, marked auto.</summary>
    public static void ResolveFallback(MergePlan plan)
    {
        foreach (var item in plan.Unresolved.ToList())
        {
            item.ChosenSourceId = item.Options[^1].SourceId;
            item.AutoResolved = true;
        }
    }

    private static Dictionary<string, Dictionary<string, (string Source, string Entry, bool Auto)>> ReadPriorChoices(GameEnv env)
    {
        var result = new Dictionary<string, Dictionary<string, (string, string, bool)>>(StringComparer.Ordinal);
        var marker = Path.Combine(env.ModsDir, FolderName, MarkerFile);
        if (!File.Exists(marker)) return result;
        JsonNode? root;
        try { root = JsonNode.Parse(File.ReadAllText(marker)); }
        catch (JsonException) { return result; }

        foreach (var p in (root?["pools"] as JsonArray) ?? new JsonArray())
        {
            var key = $"{p?["type"]?.GetValue<string>()}/{p?["strName"]?.GetValue<string>()}";
            if (p?["choices"] is not JsonObject choices) continue;
            var map = new Dictionary<string, (string, string, bool)>(StringComparer.Ordinal);
            foreach (var (token, val) in choices)
            {
                if (val is not JsonObject o) continue;
                map[token] = (
                    o["source"]?.GetValue<string>() ?? "",
                    o["entry"]?.GetValue<string>() ?? "",
                    o["auto"]?.GetValue<bool>() ?? false);
            }
            result[key] = map;
        }
        return result;
    }

    // ------------------------------------------------------------ generate ---

    /// <summary>Writes the patch mod from a fully resolved plan and registers it last.</summary>
    public static List<string> Generate(GameEnv env, MergePlan plan, string? installedVersion, string toolVersion)
    {
        if (plan.Pools.Count == 0)
            throw new InvalidOperationException("nothing to patch - there are no partial-overlap shop-pool conflicts.");
        if (plan.Unresolved.Any())
            throw new InvalidOperationException("the merge plan still has undecided items - resolve them first.");

        var dir = Path.Combine(env.ModsDir, FolderName);
        Directory.CreateDirectory(Path.Combine(dir, "data", "loot"));

        var poolNodes = new JsonArray();
        var markerPools = new JsonArray();
        var mergedDescriptions = new List<string>();

        foreach (var p in plan.Pools)
        {
            var obj = p.BaseObject;
            obj["aLoots"] = new JsonArray(p.LootItems.Select(i => (JsonNode)i.Resolved.Entry).ToArray());
            obj["aCOs"] = new JsonArray(p.CoItems.Select(i => (JsonNode)i.Resolved.Entry).ToArray());
            poolNodes.Add(obj);

            var sources = new JsonArray();
            foreach (var m in p.Collision.Claimants)
                sources.Add(new JsonObject
                {
                    ["id"] = SourceId(m),
                    ["label"] = m.Label,
                    ["hash"] = ItemsHash(m.Claims[(p.Collision.Type, p.Collision.ObjName)]!),
                });

            var choices = new JsonObject();
            foreach (var i in p.AllItems.Where(i => i.Contested))
                choices[i.Token] = new JsonObject
                {
                    ["source"] = i.Resolved.SourceId,
                    ["entry"] = i.Resolved.Entry,
                    ["auto"] = i.AutoResolved,
                };

            markerPools.Add(new JsonObject
            {
                ["type"] = p.Collision.Type,
                ["strName"] = p.Collision.ObjName,
                ["sources"] = sources,
                ["choices"] = choices,
            });
            mergedDescriptions.Add($"{p.Collision.ObjName} = {string.Join(" + ", p.Collision.Claimants.Select(m => m.DisplayName ?? m.Name))}");
        }

        File.WriteAllText(Path.Combine(dir, "data", "loot", "loot.json"), poolNodes.ToJsonString(Indented) + "\n");

        var modInfo = new JsonArray(new JsonObject
        {
            ["strName"] = "Ostrasort Patch",
            ["strAuthor"] = "Ostrasort",
            ["strModURL"] = "",
            ["strGameVersion"] = installedVersion ?? "",
            ["strModVersion"] = toolVersion,
            ["strNotes"] = "Auto-generated by Ostrasort. Merges shop pools that conflicting mods both " +
                           "override, so no mod's wares are lost: " + string.Join("; ", mergedDescriptions) +
                           ". Must load LAST. Do not edit by hand - re-run Ostrasort's patch after any " +
                           "of the merged mods update, or remove it with --unpatch / the Remove button.",
            ["strWorkshopID"] = "",
        });
        File.WriteAllText(Path.Combine(dir, "mod_info.json"), modInfo.ToJsonString(Indented) + "\n");

        var marker = new JsonObject
        {
            ["toolVersion"] = toolVersion,
            ["generatedUtc"] = DateTime.UtcNow.ToString("o"),
            ["pools"] = markerPools,
        };
        File.WriteAllText(Path.Combine(dir, MarkerFile), marker.ToJsonString(Indented) + "\n");

        EnsureRegisteredLast(env);
        return mergedDescriptions;
    }

    /// <summary>Finds one object by strName in a mod's data\&lt;type&gt; folder and deep-clones it.</summary>
    private static JsonNode? LoadPoolObject(string modDir, string type, string strName)
    {
        var typeDir = Path.Combine(modDir, "data", type);
        if (!Directory.Exists(typeDir)) return null;
        foreach (var file in Directory.EnumerateFiles(typeDir, "*.json", SearchOption.AllDirectories))
        {
            // duplicate property names throw ArgumentException on first ACCESS
            // of a lazily-materialized JsonNode - keep the walk inside the try
            try
            {
                var root = JsonNode.Parse(File.ReadAllText(file), null, Lenient);
                var objects = root is JsonArray arr ? arr.ToList() : new List<JsonNode?> { root };
                foreach (var o in objects)
                    if (o?["strName"]?.GetValue<string>() == strName)
                        return o.DeepClone();
            }
            catch (JsonException) { }
            catch (ArgumentException) { }
            catch (InvalidOperationException) { }
        }
        return null;
    }

    // -------------------------------------------------- register / remove ---

    private static void EnsureRegisteredLast(GameEnv env)
    {
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit")
            .Append(FolderName).ToList();
        if (!target.SequenceEqual(lo.Order)) lo.Write(target);
    }

    public static void Remove(GameEnv env)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        if (Directory.Exists(dir))
        {
            if (!File.Exists(Path.Combine(dir, MarkerFile)))
                throw new InvalidOperationException(
                    $"'{dir}' has no {MarkerFile} - refusing to delete a folder Ostrasort did not generate.");
            Directory.Delete(dir, recursive: true);
        }
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit").ToList();
        if (target.Count != lo.Order.Count) lo.Write(target);
    }
}
