using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Ostrasort;

public sealed class PatchInfo
{
    public bool Exists { get; init; }
    public string? Dir { get; init; }
    public string? ToolVersion { get; set; }
    public int ExcludedCount { get; set; }        // items the player rejected outright
    public List<string> CoveredKeys { get; } = new();
    public List<string> StaleReasons { get; } = new();
    public List<string> UnneededKeys { get; } = new();
    public bool Stale => StaleReasons.Count > 0;
    public bool Obsolete => Exists && CoveredKeys.Count == 0 && !Stale;   // conflicts resolved upstream
}

// ------------------------------------------------------------- merge plan ---

/// <summary>
/// One mod's candidate for a merge item. For a loot pool the candidate is the
/// entry string ("ItmChair01Loose=1.0x21"); for an object field the candidate
/// is a JSON value carried in <see cref="Node"/> (with Entry a compact display
/// of it). The synthetic source id "__union__" marks a computed array union.
/// </summary>
public sealed record MergeOption(string SourceId, string SourceLabel, string Entry, JsonNode? Node = null);

/// <summary>
/// One decision in a merge. For loot pools the token is an item name and each
/// option is that item's entry from one mod; for object merges the token is a
/// field name and each option is that field's value from one mod. Contested =
/// the options disagree and a decision is needed (the player's, or a fallback).
/// Excluded drops a loot item / reverts an object field to the base value.
/// </summary>
public sealed class MergeItem
{
    public required string Token { get; init; }
    public required List<MergeOption> Options { get; init; }
    public JsonNode? BaseNode { get; init; }      // object merges: the vanilla value (exclude reverts here)
    public bool IsArrayField { get; init; }       // object merges: an a* field (a union option is offered)
    public string? ChosenSourceId { get; set; }
    public bool AutoResolved { get; set; }        // decided by the headless fallback, not a person
    public bool Excluded { get; set; }            // drop (loot) / revert to vanilla (field)

    public bool Contested => Options.Select(o => o.Entry).Distinct(StringComparer.Ordinal).Count() > 1;
    public bool NeedsDecision => Contested && ChosenSourceId is null && !Excluded;
    public MergeOption Resolved =>
        Options.LastOrDefault(o => o.SourceId == ChosenSourceId) ?? Options[^1];
}

/// <summary>A colliding shop/loot pool being merged into a union.</summary>
public sealed class PoolPlan
{
    public required Collision Collision { get; init; }
    public required JsonNode BaseObject { get; init; }     // last claimant's object (non-pool fields win)
    public required List<MergeItem> LootItems { get; init; }
    public required List<MergeItem> CoItems { get; init; }
    public IEnumerable<MergeItem> AllItems => LootItems.Concat(CoItems);
}

/// <summary>A colliding non-loot object being field-merged (3-way, core = base).</summary>
public sealed class ObjectPlan
{
    public required Collision Collision { get; init; }
    public required string Type { get; init; }
    public required JsonNode BaseObject { get; init; }     // core version (clone); merged fields overlay it
    public required List<MergeItem> Fields { get; init; }  // only the fields that changed vs core
    public List<string> SchemaErrors { get; } = new();
}

public sealed class MergePlan
{
    public required List<PoolPlan> Pools { get; init; }
    public List<ObjectPlan> Objects { get; init; } = new();

    public IEnumerable<MergeItem> AllItems =>
        Pools.SelectMany(p => p.AllItems).Concat(Objects.SelectMany(o => o.Fields));
    public IEnumerable<MergeItem> Unresolved => AllItems.Where(i => i.NeedsDecision);
    public IEnumerable<MergeItem> ContestedItems => AllItems.Where(i => i.Contested);
    public bool IsEmpty => Pools.Count == 0 && Objects.Count == 0;
}

/// <summary>Outcome of generating the patch: what was merged, and any schema warnings on merged objects.</summary>
public sealed record GenerateResult(List<string> Merged, List<string> SchemaWarnings);

/// <summary>
/// Generates and maintains the "OstrasortPatch" mod: for shop-pool collisions
/// where neither mod's pool covers the other (no load order fixes those), it
/// writes a merged union pool that loads last. Items only one mod stocks are
/// always kept; items with disagreeing entries are decided by the player (the
/// resolver UI) or, headless, fall back to the later-loaded mod's entry and
/// are marked auto so the next interactive run offers them for review.
/// The folder is wholly owned by Ostrasort: never hand-edited, safe to delete,
/// regenerated by --patch, removed by --unpatch. A marker file records the
/// source pools (for staleness detection) and every decision (so they stick).
/// </summary>
public static class Patcher
{
    public const string FolderName = "OstrasortPatch";
    public const string MarkerFile = "ostrasort_patch.json";

    private static readonly JsonDocumentOptions Lenient = new()
    {
        AllowTrailingCommas = true,
        CommentHandling = JsonCommentHandling.Skip,
    };
    private static readonly JsonSerializerOptions Indented = new() { WriteIndented = true };

    /// <summary>Loot pools --patch can merge: every claimant has aLoots and some pair is a partial overlap.</summary>
    public static List<Collision> PatchableConflicts(Analysis a) =>
        a.Collisions.Where(c =>
            c.Type == "loot" &&
            c.Claimants.All(m => m.Claims.TryGetValue((c.Type, c.ObjName), out var l) && l is not null) &&
            c.Pairs.Any(p => p.Rel == Relation.Partial)).ToList();

    /// <summary>Non-loot objects a 3-way field merge would improve on (flagged by FieldDiff).</summary>
    public static List<Collision> MergeableObjects(Analysis a) =>
        a.Collisions.Where(c => c.ObjectMergeable).ToList();

    /// <summary>Everything --patch can act on - loot pools plus mergeable objects.</summary>
    public static bool HasWork(Analysis a) => PatchableConflicts(a).Count > 0 || MergeableObjects(a).Count > 0;

    public static string ItemsHash(IEnumerable<string> loots) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(
            string.Join("\n", loots.OrderBy(x => x, StringComparer.Ordinal)))));

    private static string SourceId(ModEntry m) => m.Dir ?? m.Raw;

    /// <summary>Per-source signature for staleness: the aLoots for a loot pool, the whole object otherwise.</summary>
    private static string SourceSig(GameEnv env, Collision c, ModEntry m)
    {
        if (m.Claims.TryGetValue((c.Type, c.ObjName), out var loots) && loots is not null)
            return ItemsHash(loots);
        if (m.Dir is null) return "";
        var obj = FieldDiff.LoadObject(Path.Combine(m.Dir, "data", c.Type), c.ObjName);
        return obj is null ? "" : ItemsHash(new[] { obj.ToJsonString() });
    }

    // ------------------------------------------------------------- inspect ---

    /// <summary>
    /// Reads the marker of an existing patch, verifies it against the current
    /// conflicts, and marks collisions it freshly covers as resolved.
    /// </summary>
    public static PatchInfo Inspect(GameEnv env, Analysis a)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        var marker = Path.Combine(dir, MarkerFile);
        if (!File.Exists(marker))
            return new PatchInfo { Exists = false, Dir = Directory.Exists(dir) ? dir : null };

        var info = new PatchInfo { Exists = true, Dir = dir };
        JsonNode? root;
        try { root = JsonNode.Parse(File.ReadAllText(marker)); }
        catch (JsonException)
        {
            info.StaleReasons.Add("the patch marker file is unreadable - regenerate the patch");
            return info;
        }
        info.ToolVersion = root?["toolVersion"]?.GetValue<string>();

        // marker pool key -> ordered (id, hash) sources it was generated from
        var markerPools = new Dictionary<string, List<(string Id, string Hash)>>(StringComparer.Ordinal);
        foreach (var p in (root?["pools"] as JsonArray) ?? new JsonArray())
        {
            var key = $"{p?["type"]?.GetValue<string>()}/{p?["strName"]?.GetValue<string>()}";
            var sources = new List<(string, string)>();
            foreach (var s in (p?["sources"] as JsonArray) ?? new JsonArray())
                sources.Add((s?["id"]?.GetValue<string>() ?? "", s?["hash"]?.GetValue<string>() ?? ""));
            markerPools[key] = sources;
            if (p?["choices"] is JsonObject choices)
                info.ExcludedCount += choices.Count(kv => (kv.Value as JsonObject)?["excluded"]?.GetValue<bool>() == true);
        }

        var current = PatchableConflicts(a).Concat(MergeableObjects(a)).ToList();
        foreach (var c in current)
        {
            if (!markerPools.TryGetValue(c.Key, out var sources))
            {
                info.StaleReasons.Add($"new conflict {c.Key} is not covered yet");
                continue;
            }
            var now = c.Claimants.Select(m => (Id: SourceId(m), Hash: SourceSig(env, c, m))).ToList();
            if (!now.SequenceEqual(sources))
            {
                info.StaleReasons.Add($"{c.Key}: a source mod's data (or the mod order) changed since generation");
                continue;
            }
            info.CoveredKeys.Add(c.Key);
            c.ResolvedByPatch = true;
        }
        foreach (var key in markerPools.Keys.Where(k => current.All(c => c.Key != k)))
            info.UnneededKeys.Add(key);

        return info;
    }

    // ---------------------------------------------------------------- plan ---

    /// <summary>
    /// Builds the merge plan for every patchable conflict. Prior decisions are
    /// pre-applied from the marker when the chosen source still offers exactly
    /// the same entry; anything new or changed comes back as needing a decision.
    /// With <paramref name="fresh"/>, prior decisions (including exclusions)
    /// are discarded and everything contested is asked again.
    /// </summary>
    public static MergePlan PlanMerge(GameEnv env, Analysis a, bool fresh = false)
    {
        var prior = fresh
            ? new Dictionary<string, Dictionary<string, (string, string, bool, bool)>>()
            : ReadPriorChoices(env);
        var pools = new List<PoolPlan>();

        foreach (var c in PatchableConflicts(a))
        {
            var lootOptions = new Dictionary<string, List<MergeOption>>(StringComparer.Ordinal);
            var lootOrder = new List<string>();
            var coOptions = new Dictionary<string, List<MergeOption>>(StringComparer.Ordinal);
            var coOrder = new List<string>();
            JsonNode? baseObj = null;

            foreach (var m in c.Claimants)
            {
                var obj = LoadPoolObject(m.Dir!, c.Type, c.ObjName);
                if (obj is null) continue;
                baseObj = obj;                       // last claimant's object = base
                Collect(obj["aLoots"], m, lootOrder, lootOptions);
                Collect(obj["aCOs"], m, coOrder, coOptions);
            }
            if (baseObj is null) continue;

            prior.TryGetValue(c.Key, out var priorChoices);
            var plan = new PoolPlan
            {
                Collision = c,
                BaseObject = baseObj,
                LootItems = lootOrder.Select(t => BuildItem(t, lootOptions[t], priorChoices)).ToList(),
                CoItems = coOrder.Select(t => BuildItem(t, coOptions[t], priorChoices)).ToList(),
            };
            pools.Add(plan);
        }

        // non-loot object merges (3-way field merge, core = base)
        var objects = new List<ObjectPlan>();
        foreach (var c in MergeableObjects(a))
        {
            var coreObj = FieldDiff.LoadObject(Path.Combine(env.CoreDataDir, c.Type), c.ObjName);
            if (coreObj is null) continue;
            var versions = c.Claimants.Where(m => m.Dir is not null)
                .Select(m => (Mod: m, Obj: FieldDiff.LoadObject(Path.Combine(m.Dir!, "data", c.Type), c.ObjName)))
                .Where(x => x.Obj is not null)
                .Select(x => (x.Mod, x.Obj!))
                .ToList();
            var plan = ObjectMerge.Build(c, coreObj, versions);
            if (plan is null) continue;

            prior.TryGetValue(c.Key, out var priorChoices);
            foreach (var f in plan.Fields) ApplyPrior(f, priorChoices);
            objects.Add(plan);
        }

        return new MergePlan { Pools = pools, Objects = objects };
    }

    private static void Collect(JsonNode? array, ModEntry source, List<string> order,
                                Dictionary<string, List<MergeOption>> options)
    {
        if (array is not JsonArray ja) return;
        foreach (var n in ja)
        {
            if (n?.GetValueKind() != JsonValueKind.String) continue;
            var entry = n.GetValue<string>();
            var token = entry.Split('=')[0];
            if (!options.TryGetValue(token, out var list))
            {
                options[token] = list = new List<MergeOption>();
                order.Add(token);
            }
            list.Add(new MergeOption(SourceId(source), source.DisplayName ?? source.Name, entry));
        }
    }

    private static MergeItem BuildItem(string token, List<MergeOption> options,
                                       Dictionary<string, (string Source, string Entry, bool Auto, bool Excluded)>? prior)
    {
        var item = new MergeItem { Token = token, Options = options };
        ApplyPrior(item, prior);
        return item;
    }

    /// <summary>Re-applies a stored decision (source pick or exclusion) to an item if still valid.</summary>
    private static void ApplyPrior(MergeItem item,
                                   Dictionary<string, (string Source, string Entry, bool Auto, bool Excluded)>? prior)
    {
        if (prior is null || !prior.TryGetValue(item.Token, out var p)) return;
        if (p.Excluded)
        {
            item.Excluded = true;               // intent about the item/field - survives value changes
            item.ChosenSourceId = null;
        }
        else if (item.Contested && item.Options.Any(o => o.SourceId == p.Source && o.Entry == p.Entry))
        {
            item.ChosenSourceId = p.Source;     // decision still valid - keep it
            item.AutoResolved = p.Auto;
        }
    }

    /// <summary>Headless fallback: unresolved contested items take the later-loaded entry, marked auto.</summary>
    public static void ResolveFallback(MergePlan plan)
    {
        foreach (var item in plan.Unresolved.ToList())
        {
            item.ChosenSourceId = item.Options[^1].SourceId;
            item.AutoResolved = true;
        }
    }

    private static Dictionary<string, Dictionary<string, (string Source, string Entry, bool Auto, bool Excluded)>> ReadPriorChoices(GameEnv env)
    {
        var result = new Dictionary<string, Dictionary<string, (string, string, bool, bool)>>(StringComparer.Ordinal);
        var marker = Path.Combine(env.ModsDir, FolderName, MarkerFile);
        if (!File.Exists(marker)) return result;
        JsonNode? root;
        try { root = JsonNode.Parse(File.ReadAllText(marker)); }
        catch (JsonException) { return result; }

        foreach (var p in (root?["pools"] as JsonArray) ?? new JsonArray())
        {
            var key = $"{p?["type"]?.GetValue<string>()}/{p?["strName"]?.GetValue<string>()}";
            if (p?["choices"] is not JsonObject choices) continue;
            var map = new Dictionary<string, (string, string, bool, bool)>(StringComparer.Ordinal);
            foreach (var (token, val) in choices)
            {
                if (val is not JsonObject o) continue;
                map[token] = (
                    o["source"]?.GetValue<string>() ?? "",
                    o["entry"]?.GetValue<string>() ?? "",
                    o["auto"]?.GetValue<bool>() ?? false,
                    o["excluded"]?.GetValue<bool>() ?? false);
            }
            result[key] = map;
        }
        return result;
    }

    // ------------------------------------------------------------ generate ---

    /// <summary>Writes the patch mod from a fully resolved plan and registers it last.</summary>
    public static GenerateResult Generate(GameEnv env, MergePlan plan, string? installedVersion, string toolVersion)
    {
        if (plan.IsEmpty)
            throw new InvalidOperationException("nothing to patch - there are no mergeable conflicts.");
        if (plan.Unresolved.Any())
            throw new InvalidOperationException("the merge plan still has undecided items - resolve them first.");

        var dir = Path.Combine(env.ModsDir, FolderName);
        var validator = new SchemaValidator(env);
        var markerPools = new JsonArray();
        var descriptions = new List<string>();
        var schemaWarnings = new List<string>();

        JsonArray SourcesFor(Collision c)
        {
            var arr = new JsonArray();
            foreach (var m in c.Claimants)
                arr.Add(new JsonObject { ["id"] = SourceId(m), ["label"] = m.Label, ["hash"] = SourceSig(env, c, m) });
            return arr;
        }
        JsonObject ChoicesFor(IEnumerable<MergeItem> items)
        {
            var choices = new JsonObject();
            foreach (var i in items.Where(i => i.Excluded))
                choices[i.Token] = new JsonObject { ["excluded"] = true };
            foreach (var i in items.Where(i => i.Contested && !i.Excluded))
                choices[i.Token] = new JsonObject
                {
                    ["source"] = i.Resolved.SourceId,
                    ["entry"] = i.Resolved.Entry,
                    ["auto"] = i.AutoResolved,
                };
            return choices;
        }

        // ---- loot pools -> data/loot/loot.json (per-item union) ----
        if (plan.Pools.Count > 0)
        {
            Directory.CreateDirectory(Path.Combine(dir, "data", "loot"));
            var poolNodes = new JsonArray();
            foreach (var p in plan.Pools)
            {
                var obj = p.BaseObject;
                obj["aLoots"] = new JsonArray(p.LootItems.Where(i => !i.Excluded).Select(i => (JsonNode)i.Resolved.Entry).ToArray());
                obj["aCOs"] = new JsonArray(p.CoItems.Where(i => !i.Excluded).Select(i => (JsonNode)i.Resolved.Entry).ToArray());
                poolNodes.Add(obj);
                markerPools.Add(new JsonObject
                {
                    ["type"] = p.Collision.Type,
                    ["strName"] = p.Collision.ObjName,
                    ["kind"] = "loot",
                    ["sources"] = SourcesFor(p.Collision),
                    ["choices"] = ChoicesFor(p.AllItems),
                });
                descriptions.Add($"{p.Collision.ObjName} = {string.Join(" + ", p.Collision.Claimants.Select(m => m.DisplayName ?? m.Name))}");
            }
            File.WriteAllText(Path.Combine(dir, "data", "loot", "loot.json"), poolNodes.ToJsonString(Indented) + "\n");
        }

        // ---- object merges -> data/<type>/ostrasort_merged.json (field merge, schema-validated) ----
        foreach (var byType in plan.Objects.GroupBy(o => o.Type))
        {
            Directory.CreateDirectory(Path.Combine(dir, "data", byType.Key));
            var arr = new JsonArray();
            foreach (var o in byType)
            {
                var merged = ObjectMerge.Assemble(o);
                var errs = validator.Validate(merged, o.Type);
                if (errs.Count > 0)
                {
                    o.SchemaErrors.AddRange(errs);
                    schemaWarnings.Add($"{o.Type}/{o.Collision.ObjName}: " +
                        string.Join("; ", errs.Take(3)) + (errs.Count > 3 ? $" (+{errs.Count - 3} more)" : ""));
                }
                arr.Add(merged);

                var marker = new JsonObject
                {
                    ["type"] = o.Type,
                    ["strName"] = o.Collision.ObjName,
                    ["kind"] = "object",
                    ["sources"] = SourcesFor(o.Collision),
                    ["choices"] = ChoicesFor(o.Fields),
                };
                if (o.SchemaErrors.Count > 0)
                    marker["schemaErrors"] = new JsonArray(o.SchemaErrors.Select(e => (JsonNode)e).ToArray());
                markerPools.Add(marker);

                var kept = o.Fields.Count(f => !f.Excluded);
                descriptions.Add($"{o.Collision.ObjName} (merged {kept} field(s))");
            }
            File.WriteAllText(Path.Combine(dir, "data", byType.Key, "ostrasort_merged.json"), arr.ToJsonString(Indented) + "\n");
        }

        var poolCount = plan.Pools.Count;
        var objCount = plan.Objects.Count;
        var summary = string.Join(" and ", new[]
        {
            poolCount > 0 ? $"{poolCount} shop pool(s)" : null,
            objCount > 0 ? $"{objCount} object(s)" : null,
        }.Where(x => x != null));

        var modInfo = new JsonArray(new JsonObject
        {
            ["strName"] = "Ostrasort Patch",
            ["strAuthor"] = "Ostrasort",
            ["strModURL"] = "",
            ["strGameVersion"] = installedVersion ?? "",
            ["strModVersion"] = toolVersion,
            ["strNotes"] = $"Auto-generated by Ostrasort. Merges {summary} that conflicting mods both " +
                           "override, so no mod's changes are lost: " + string.Join("; ", descriptions) +
                           ". Must load LAST. Do not edit by hand - re-run Ostrasort's patch after any " +
                           "of the merged mods update, or remove it with --unpatch / the Remove button.",
            ["strWorkshopID"] = "",
        });
        File.WriteAllText(Path.Combine(dir, "mod_info.json"), modInfo.ToJsonString(Indented) + "\n");

        var markerRoot = new JsonObject
        {
            ["toolVersion"] = toolVersion,
            ["generatedUtc"] = DateTime.UtcNow.ToString("o"),
            ["pools"] = markerPools,
        };
        File.WriteAllText(Path.Combine(dir, MarkerFile), markerRoot.ToJsonString(Indented) + "\n");

        EnsureRegisteredLast(env);
        return new GenerateResult(descriptions, schemaWarnings);
    }

    /// <summary>Finds one object by strName in a mod's data\&lt;type&gt; folder and deep-clones it.</summary>
    private static JsonNode? LoadPoolObject(string modDir, string type, string strName)
    {
        var typeDir = Path.Combine(modDir, "data", type);
        if (!Directory.Exists(typeDir)) return null;
        foreach (var file in Directory.EnumerateFiles(typeDir, "*.json", SearchOption.AllDirectories))
        {
            // duplicate property names throw ArgumentException on first ACCESS
            // of a lazily-materialized JsonNode - keep the walk inside the try
            try
            {
                var root = JsonNode.Parse(File.ReadAllText(file), null, Lenient);
                var objects = root is JsonArray arr ? arr.ToList() : new List<JsonNode?> { root };
                foreach (var o in objects)
                    if (o?["strName"]?.GetValue<string>() == strName)
                        return o.DeepClone();
            }
            catch (JsonException) { }
            catch (ArgumentException) { }
            catch (InvalidOperationException) { }
        }
        return null;
    }

    // -------------------------------------------------- register / remove ---

    private static void EnsureRegisteredLast(GameEnv env)
    {
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit")
            .Append(FolderName).ToList();
        if (!target.SequenceEqual(lo.Order)) lo.Write(target);
    }

    public static void Remove(GameEnv env)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        if (Directory.Exists(dir))
        {
            if (!File.Exists(Path.Combine(dir, MarkerFile)))
                throw new InvalidOperationException(
                    $"'{dir}' has no {MarkerFile} - refusing to delete a folder Ostrasort did not generate.");
            Directory.Delete(dir, recursive: true);
        }
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit").ToList();
        if (target.Count != lo.Order.Count) lo.Write(target);
    }
}
