using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Ostrasort;

public sealed class PatchInfo
{
    public bool Exists { get; init; }
    public string? Dir { get; init; }
    public string? ToolVersion { get; set; }
    public List<string> CoveredKeys { get; } = new();
    public List<string> StaleReasons { get; } = new();
    public List<string> UnneededKeys { get; } = new();
    public bool Stale => StaleReasons.Count > 0;
    public bool Obsolete => Exists && CoveredKeys.Count == 0 && !Stale;   // conflicts resolved upstream
}

/// <summary>
/// Generates and maintains the "OstrasortPatch" mod: for shop-pool collisions
/// where neither mod's pool covers the other (no load order fixes those), it
/// writes a merged union pool that loads last - the LOOT "bashed patch" idea.
/// The folder is wholly owned by Ostrasort: never hand-edited, safe to delete,
/// regenerated by --patch, removed by --unpatch. A marker file records the
/// source pools so staleness is detected when any source mod updates.
///
/// PROVISIONAL merge rule (pending user decision): per item, the LATER-loaded
/// mod's entry wins - the same last-wins the game applies to whole objects,
/// at item grain. Items only one side stocks are all kept.
/// </summary>
public static class Patcher
{
    public const string FolderName = "OstrasortPatch";
    public const string MarkerFile = "ostrasort_patch.json";

    private static readonly JsonDocumentOptions Lenient = new()
    {
        AllowTrailingCommas = true,
        CommentHandling = JsonCommentHandling.Skip,
    };
    private static readonly JsonSerializerOptions Indented = new() { WriteIndented = true };

    /// <summary>Collisions --patch can merge: loot pools, every claimant has aLoots, some pair is Partial.</summary>
    public static List<Collision> PatchableConflicts(Analysis a) =>
        a.Collisions.Where(c =>
            c.Type == "loot" &&
            c.Claimants.All(m => m.Claims.TryGetValue((c.Type, c.ObjName), out var l) && l is not null) &&
            c.Pairs.Any(p => p.Rel == Relation.Partial)).ToList();

    public static string ItemsHash(IEnumerable<string> loots) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(
            string.Join("\n", loots.OrderBy(x => x, StringComparer.Ordinal)))));

    private static string SourceId(ModEntry m) => m.Dir ?? m.Raw;

    // ------------------------------------------------------------- inspect ---

    /// <summary>
    /// Reads the marker of an existing patch, verifies it against the current
    /// conflicts, and marks collisions it freshly covers as resolved.
    /// </summary>
    public static PatchInfo Inspect(GameEnv env, Analysis a)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        var marker = Path.Combine(dir, MarkerFile);
        if (!File.Exists(marker))
            return new PatchInfo { Exists = false, Dir = Directory.Exists(dir) ? dir : null };

        var info = new PatchInfo { Exists = true, Dir = dir };
        JsonNode? root;
        try { root = JsonNode.Parse(File.ReadAllText(marker)); }
        catch (JsonException)
        {
            info.StaleReasons.Add("the patch marker file is unreadable - re-run --patch");
            return info;
        }
        info.ToolVersion = root?["toolVersion"]?.GetValue<string>();

        // marker pool key -> ordered (id, hash) sources it was generated from
        var markerPools = new Dictionary<string, List<(string Id, string Hash)>>(StringComparer.Ordinal);
        foreach (var p in (root?["pools"] as JsonArray) ?? new JsonArray())
        {
            var key = $"{p?["type"]?.GetValue<string>()}/{p?["strName"]?.GetValue<string>()}";
            var sources = new List<(string, string)>();
            foreach (var s in (p?["sources"] as JsonArray) ?? new JsonArray())
                sources.Add((s?["id"]?.GetValue<string>() ?? "", s?["hash"]?.GetValue<string>() ?? ""));
            markerPools[key] = sources;
        }

        var current = PatchableConflicts(a);
        foreach (var c in current)
        {
            if (!markerPools.TryGetValue(c.Key, out var sources))
            {
                info.StaleReasons.Add($"new conflict {c.Key} is not covered yet");
                continue;
            }
            var now = c.Claimants
                .Select(m => (Id: SourceId(m), Hash: ItemsHash(m.Claims[(c.Type, c.ObjName)]!)))
                .ToList();
            if (!now.SequenceEqual(sources))
            {
                info.StaleReasons.Add($"{c.Key}: a source mod's pool (or the mod order) changed since generation");
                continue;
            }
            info.CoveredKeys.Add(c.Key);
            c.ResolvedByPatch = true;
        }
        foreach (var key in markerPools.Keys.Where(k => current.All(c => c.Key != k)))
            info.UnneededKeys.Add(key);

        return info;
    }

    // ------------------------------------------------------------ generate ---

    public static List<string> Generate(GameEnv env, Analysis a, string? installedVersion, string toolVersion)
    {
        var conflicts = PatchableConflicts(a);
        if (conflicts.Count == 0)
            throw new InvalidOperationException("nothing to patch - there are no partial-overlap shop-pool conflicts.");

        var dir = Path.Combine(env.ModsDir, FolderName);
        Directory.CreateDirectory(Path.Combine(dir, "data", "loot"));

        var poolNodes = new JsonArray();
        var markerPools = new JsonArray();
        var mergedDescriptions = new List<string>();

        foreach (var c in conflicts)
        {
            // per item, later-loaded claimant wins (PROVISIONAL rule); item order =
            // first-seen, so the earliest mod's arrangement leads and unique
            // late-comers append
            var lootOrder = new List<string>(); var lootChosen = new Dictionary<string, string>(StringComparer.Ordinal);
            var coOrder = new List<string>(); var coChosen = new Dictionary<string, string>(StringComparer.Ordinal);
            JsonNode? baseObj = null;
            foreach (var m in c.Claimants)
            {
                var obj = LoadPoolObject(m.Dir!, c.Type, c.ObjName);
                if (obj is null) continue;
                baseObj = obj;                       // last claimant's object = base (its other fields win)
                Fold(obj["aLoots"], lootOrder, lootChosen);
                Fold(obj["aCOs"], coOrder, coChosen);
            }
            if (baseObj is null) continue;
            baseObj["aLoots"] = new JsonArray(lootOrder.Select(t => (JsonNode)lootChosen[t]).ToArray());
            baseObj["aCOs"] = new JsonArray(coOrder.Select(t => (JsonNode)coChosen[t]).ToArray());
            poolNodes.Add(baseObj);

            var sources = new JsonArray();
            foreach (var m in c.Claimants)
                sources.Add(new JsonObject
                {
                    ["id"] = SourceId(m),
                    ["label"] = m.Label,
                    ["hash"] = ItemsHash(m.Claims[(c.Type, c.ObjName)]!),
                });
            markerPools.Add(new JsonObject { ["type"] = c.Type, ["strName"] = c.ObjName, ["sources"] = sources });
            mergedDescriptions.Add($"{c.ObjName} = {string.Join(" + ", c.Claimants.Select(m => m.DisplayName ?? m.Name))}");
        }

        File.WriteAllText(Path.Combine(dir, "data", "loot", "loot.json"), poolNodes.ToJsonString(Indented) + "\n");

        var modInfo = new JsonArray(new JsonObject
        {
            ["strName"] = "Ostrasort Patch",
            ["strAuthor"] = "Ostrasort",
            ["strModURL"] = "",
            ["strGameVersion"] = installedVersion ?? "",
            ["strModVersion"] = toolVersion,
            ["strNotes"] = "Auto-generated by Ostrasort. Merges shop pools that conflicting mods both " +
                           "override, so no mod's wares are lost: " + string.Join("; ", mergedDescriptions) +
                           ". Must load LAST. Do not edit by hand - re-run 'Ostrasort --patch' after any " +
                           "of the merged mods update, or 'Ostrasort --unpatch' to remove this.",
            ["strWorkshopID"] = "",
        });
        File.WriteAllText(Path.Combine(dir, "mod_info.json"), modInfo.ToJsonString(Indented) + "\n");

        var marker = new JsonObject
        {
            ["toolVersion"] = toolVersion,
            ["generatedUtc"] = DateTime.UtcNow.ToString("o"),
            ["pools"] = markerPools,
        };
        File.WriteAllText(Path.Combine(dir, MarkerFile), marker.ToJsonString(Indented) + "\n");

        EnsureRegisteredLast(env);
        return mergedDescriptions;
    }

    private static void Fold(JsonNode? array, List<string> order, Dictionary<string, string> chosen)
    {
        if (array is not JsonArray ja) return;
        foreach (var n in ja)
        {
            if (n?.GetValueKind() != JsonValueKind.String) continue;
            var entry = n.GetValue<string>();
            var token = entry.Split('=')[0];
            if (!chosen.ContainsKey(token)) order.Add(token);
            chosen[token] = entry;   // later claimant overwrites = later wins
        }
    }

    /// <summary>Finds one object by strName in a mod's data\&lt;type&gt; folder and deep-clones it.</summary>
    private static JsonNode? LoadPoolObject(string modDir, string type, string strName)
    {
        var typeDir = Path.Combine(modDir, "data", type);
        if (!Directory.Exists(typeDir)) return null;
        foreach (var file in Directory.EnumerateFiles(typeDir, "*.json", SearchOption.AllDirectories))
        {
            JsonNode? root;
            try { root = JsonNode.Parse(File.ReadAllText(file), null, Lenient); }
            catch (JsonException) { continue; }
            var objects = root is JsonArray arr ? arr.ToList() : new List<JsonNode?> { root };
            foreach (var o in objects)
                if (o?["strName"]?.GetValue<string>() == strName)
                    return o.DeepClone();
        }
        return null;
    }

    // -------------------------------------------------- register / remove ---

    private static void EnsureRegisteredLast(GameEnv env)
    {
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit")
            .Append(FolderName).ToList();
        if (!target.SequenceEqual(lo.Order)) lo.Write(target);
    }

    public static void Remove(GameEnv env)
    {
        var dir = Path.Combine(env.ModsDir, FolderName);
        if (Directory.Exists(dir))
        {
            if (!File.Exists(Path.Combine(dir, MarkerFile)))
                throw new InvalidOperationException(
                    $"'{dir}' has no {MarkerFile} - refusing to delete a folder Ostrasort did not generate.");
            Directory.Delete(dir, recursive: true);
        }
        var lo = LoadOrderFile.Read(env.LoadingOrderPath);
        var target = lo.Order.Where(e => e != FolderName && e != FolderName + "|edit").ToList();
        if (target.Count != lo.Order.Count) lo.Write(target);
    }
}
