namespace Ostrasort;

public static class Report
{
    private static void Line(string text, ConsoleColor? color = null)
    {
        if (color is { } c) Console.ForegroundColor = c;
        Console.WriteLine(text);
        if (color is not null) Console.ResetColor();
    }

    public static void Print(GameEnv env, Scanner scanner, Analysis a, PatchInfo patch,
                             string version, IReadOnlyList<string> performed)
    {
        Line("");
        Line($"Ostrasort v{version} - Ostranauts load-order analyzer", ConsoleColor.Cyan);
        Line($"Game: {env.GameRoot}");
        Line($"      version {env.InstalledVersion ?? "unknown"}, found via {env.DiscoveredVia}");
        Line($"Mods: {env.ModsDir}");
        Line($"Core: {scanner.CoreIndex.Count:N0} data objects across {scanner.CoreTypes} types" +
             (scanner.CoreProblemFiles > 0 ? $" ({scanner.CoreProblemFiles} file(s) with non-standard JSON skipped or lenient-parsed)" : ""));

        if (a.Rival is { } rival)
        {
            Line("");
            Line("  !!! FFU / THUNDERSTORE STACK DETECTED - Ostrasort is Steam-Workshop-only !!!", ConsoleColor.Red);
            foreach (var e in rival.Evidence) Line($"      - {e}", ConsoleColor.Red);
            Line("      Robyn's OstraAutoloader generates loading_order.json itself; running it alongside", ConsoleColor.Yellow);
            Line("      Ostrasort makes both fight over that file and will likely break your FFU setup.", ConsoleColor.Yellow);
            Line("      Use one or the other, not both. Ostrasort refuses to write here (override:", ConsoleColor.Yellow);
            Line("      --allow-rival-stack, at your own risk).", ConsoleColor.Yellow);
        }

        // ---------------------------------------------------------- mod table
        Line("");
        Line($"MODS ({a.Registered.Count} registered)", ConsoleColor.Cyan);
        var rows = a.Registered.Select((m, i) => (Pos: (i + 1).ToString(), Mod: m))
            .Concat(a.UnregisteredLocal.Concat(a.UnregisteredWorkshop).Select(m => (Pos: "-", Mod: m)));
        Line($"  {"#",-3} {"entry",-52} {"class",-14} {"data",-18} notes");
        foreach (var (pos, m) in rows)
        {
            var cls = m.Kind == EntryKind.Core ? "core"
                    : m.IsPatch ? "patch"
                    : m.Class.ToString().ToLowerInvariant();
            var data = m.Kind == EntryKind.Core
                ? $"{scanner.CoreIndex.Count:N0} objects"
                : m.DataObjects > 0
                    ? $"{m.DataObjects} objs ({m.CoreOverrides} ovr)"
                    : "-";
            var notes = new List<string>();
            if (!m.Registered) notes.Add("NOT REGISTERED");
            if (m.Dir is null && m.Kind != EntryKind.Core) notes.Add("DEAD");
            if (m.IsPatch) notes.Add("generated by Ostrasort");
            if (m.HasPatchers) notes.Add("ships BepInEx patchers");
            if (m.HasPlugins && !m.HasPatchers) notes.Add("plugins");
            if (m.GameVersion is { Length: > 0 } gv && env.InstalledVersion is { } iv && gv != iv)
                notes.Add($"gameVersion {gv} lags {iv}");
            if (m.JsonErrors.Count > 0) notes.Add($"{m.JsonErrors.Count} JSON problem(s)");

            var label = m.Label;
            if (label.Length > 52) label = label[..49] + "...";
            var color = notes.Any(n => n.StartsWith("NOT") || n.StartsWith("DEAD") || n.Contains("JSON"))
                ? ConsoleColor.Yellow : (ConsoleColor?)null;
            Line($"  {pos,-3} {label,-52} {cls,-14} {data,-18} {string.Join("; ", notes)}", color);
        }

        // --------------------------------------------------------- collisions
        Line("");
        Line($"COLLISIONS ({a.Collisions.Count})", ConsoleColor.Cyan);
        foreach (var v in CollisionView.Build(a))   // same grouped view as the GUI
            Line(new string(' ', 2 + v.Indent * 2) + v.Text, v.Sev switch
            {
                LineSev.Good => ConsoleColor.Green,
                LineSev.Warn => ConsoleColor.Yellow,
                LineSev.Bad => ConsoleColor.Red,
                LineSev.Dim => ConsoleColor.DarkGray,
                _ => (ConsoleColor?)null,
            });

        // -------------------------------------------------------------- patch
        Line("");
        Line("PATCH", ConsoleColor.Cyan);
        if (!patch.Exists)
        {
            Line(a.HasUnresolvedConflicts
                ? "  none generated - run with --patch to merge the conflicting pools above"
                : "  none needed");
        }
        else if (patch.Stale)
        {
            foreach (var r in patch.StaleReasons) Line($"  STALE: {r}", ConsoleColor.Red);
            Line("  Re-run with --patch to regenerate it.", ConsoleColor.Red);
        }
        else if (patch.Obsolete)
        {
            Line("  the installed Ostrasort Patch is no longer needed (its conflicts resolved upstream" +
                 $"{(patch.UnneededKeys.Count > 0 ? ": " + string.Join(", ", patch.UnneededKeys) : "")})", ConsoleColor.Yellow);
            Line("  Run with --unpatch to remove it.", ConsoleColor.Yellow);
        }
        else
        {
            Line($"  fresh (v{patch.ToolVersion ?? "?"}) - covering {string.Join(", ", patch.CoveredKeys)}" +
                 (patch.ExcludedCount > 0 ? $"; {patch.ExcludedCount} item(s) excluded by you" : ""), ConsoleColor.Green);
            if (patch.UnneededKeys.Count > 0)
                Line($"  note: no longer needed for {string.Join(", ", patch.UnneededKeys)} (resolved upstream)", ConsoleColor.Yellow);
        }

        // ------------------------------------------------------------ hygiene
        Line("");
        Line($"WARNINGS ({a.Warnings.Count})", ConsoleColor.Cyan);
        if (a.Warnings.Count == 0) Line("  (none)");
        foreach (var w in a.Warnings) Line($"  ! {w}", ConsoleColor.Yellow);
        foreach (var m in a.AllMods.Where(m => m.JsonErrors.Count > 0))
            foreach (var e in m.JsonErrors)
                Line($"  ! {m.Label}: {e}", ConsoleColor.Yellow);

        // --------------------------------------------------------- suggestion
        Line("");
        Line("SUGGESTED ORDER", ConsoleColor.Cyan);
        foreach (var v in OrderChangeView.Build(a))
            Line(new string(' ', 2 + v.Indent * 2) + v.Text, v.Sev switch
            {
                LineSev.Good => ConsoleColor.Green,
                LineSev.Warn => ConsoleColor.Yellow,
                LineSev.Bad => ConsoleColor.Red,
                LineSev.Dim => ConsoleColor.DarkGray,
                _ => (ConsoleColor?)null,
            });
        if (a.OrderChanged)
            Line("\nAnalysis only - nothing more written. Re-run with --apply to write this order (a .bak is kept).",
                 ConsoleColor.Cyan);

        foreach (var act in performed)
            Line(act, ConsoleColor.Green);
    }
}
